;;; ghostty-theme.el --- Monokai blue/green accents, icy blue-black background -*- lexical-binding: t; -*-
;; Personal Emacs palette: Monokai blue/green, lavender strings and white comments.
;; Face coverage based on the existing personal GITS theme.

(deftheme ghostty "Monokai blue/green accents, icy blue-black background and white comments.")

;; Emacs-specific background; Ghostty itself keeps its existing colors.
(let ((bg        "#0b111b")
      (bg-dark   "#0e1724")
      (bg-light  "#0e1724")
      (bg-lt2    "#16283b")
      (ml-bg     "#0e1724")
      (fg        "#4fb3d4")
      (fg-dark   "#a9c7c9")
      (red       "#ff3d81")
      (orange    "#ff9e3b")
      (yellow    "#aa82e8")
      (green     "#a6e22e")
      (cyan      "#4fb3d4")
      (purple    "#996de0")
      (gray      "#a9c7c9")
      (gray-lt   "#4fb3d4")
      (gray-dk   "#3f5f6a")
      (linum     "#996de0")
      (neon      "#ff9e3b")
      (hl        "#16283b")
      (cursor    "#4fb3d4")
      (sel       "#203b53")
      (border    "#3f5f6a"))
  (custom-theme-set-faces
   'ghostty
   ;; --- temel ---
   `(default            ((t (:background ,bg :foreground ,fg))))
   `(cursor             ((t (:background ,cursor))))
   `(region             ((t (:background ,sel))))
   `(secondary-selection ((t (:background ,bg-lt2))))
   `(highlight          ((t (:background ,sel))))
   `(hl-line            ((t (:background ,hl))))
   `(fringe             ((t (:background ,bg :foreground ,gray-dk))))
   `(line-number        ((t (:foreground ,linum :background ,bg :weight bold))))
   `(line-number-current-line ((t (:foreground ,neon :background ,bg :weight bold))))
   `(vertical-border    ((t (:foreground ,gray-dk))))
   `(window-divider     ((t (:foreground ,gray-dk))))
   `(window-divider-first-pixel ((t (:foreground ,gray-dk))))
   `(window-divider-last-pixel  ((t (:foreground ,gray-dk))))
   `(minibuffer-prompt  ((t (:foreground ,green :weight bold))))
   `(shadow             ((t (:foreground ,gray))))
   `(link               ((t (:foreground ,purple :underline t))))
   `(link-visited       ((t (:foreground ,purple :underline t :weight normal))))
   `(button             ((t (:foreground ,cyan :underline t))))
   `(error              ((t (:foreground ,red :weight bold))))
   `(warning            ((t (:foreground ,orange :weight bold))))
   `(success            ((t (:foreground ,green :weight bold))))
   `(escape-glyph       ((t (:foreground ,orange :weight bold))))
   `(homoglyph          ((t (:foreground ,orange :weight bold))))
   `(nobreak-space      ((t (:foreground ,gray :underline t))))
   `(trailing-whitespace ((t (:background ,red))))
   `(whitespace-space   ((t (:foreground ,gray-dk))))
   `(whitespace-tab     ((t (:foreground ,gray-dk))))
   `(whitespace-newline ((t (:foreground ,gray-dk))))
   `(fill-column-indicator ((t (:foreground ,gray-dk))))

   ;; --- söz dizimi: font-lock + treesit (level 4) ---
   ;; Bold Edition: syntax face'ler bold.
   ;; eşleme:
   ;;   keyword/op/preproc → red | string → yellow | fn → green
   ;;   type → cyan italic | const/number → purple | comment → white
   ;;   property/param/member/attr/tag → orange | variable → lavender
   `(font-lock-keyword-face          ((t (:foreground ,red :weight bold))))
   `(font-lock-comment-face          ((t (:foreground "#ffffff" :slant italic :weight bold))))
   `(font-lock-comment-delimiter-face ((t (:foreground "#ffffff" :slant italic :weight bold))))
   `(font-lock-doc-face              ((t (:foreground "#ffffff" :slant italic :weight bold))))
   `(font-lock-doc-markup-face       ((t (:foreground ,cyan :weight bold))))
   `(font-lock-string-face           ((t (:foreground ,yellow :weight bold))))
   `(font-lock-doc-string-face       ((t (:foreground ,yellow :weight bold)))) ; eski alias
   `(font-lock-function-name-face    ((t (:foreground ,green :weight bold))))
   `(font-lock-function-call-face    ((t (:foreground ,green :weight bold))))
   ;; Variable references are lavender; parameter/member definitions are amber.
   ;; treesit çoğu param/def'i variable-name'e yazar → orange (daha renkli)
   `(font-lock-variable-name-face    ((t (:foreground ,orange :weight bold))))
   `(font-lock-variable-use-face     ((t (:foreground "#aa82e8" :weight bold))))
   `(font-lock-property-name-face    ((t (:foreground ,orange :weight bold))))
   `(font-lock-property-use-face     ((t (:foreground ,orange :weight bold))))
   `(font-lock-type-face             ((t (:foreground ,cyan :slant italic :weight bold))))
   `(font-lock-type-definition-face  ((t (:foreground ,cyan :weight bold))))
   `(font-lock-constant-face         ((t (:foreground ,purple :weight bold))))
   `(font-lock-number-face           ((t (:foreground ,purple :weight bold))))
   `(font-lock-builtin-face          ((t (:foreground ,cyan :weight bold))))
   `(font-lock-preprocessor-face     ((t (:foreground ,red :slant italic :weight bold))))
   `(font-lock-operator-face         ((t (:foreground ,red :weight bold))))
   `(font-lock-delimiter-face        ((t (:foreground ,gray-lt :weight bold))))
   `(font-lock-bracket-face          ((t (:foreground ,gray-lt :weight bold))))
   `(font-lock-punctuation-face      ((t (:foreground ,gray-lt :weight bold))))
   `(font-lock-misc-punctuation-face ((t (:foreground ,orange :weight bold))))
   `(font-lock-escape-face           ((t (:foreground ,orange :weight bold))))
   `(font-lock-negation-char-face    ((t (:foreground ,red :weight bold))))
   `(font-lock-warning-face          ((t (:foreground ,red :weight bold))))
   `(font-lock-regexp-face           ((t (:foreground ,yellow :weight bold))))
   `(font-lock-regexp-grouping-backslash  ((t (:foreground ,red :weight bold))))
   `(font-lock-regexp-grouping-construct  ((t (:foreground ,red :weight bold))))

   ;; --- arama / eşleşme ---
   `(show-paren-match   ((t (:foreground ,cursor :background ,bg-lt2 :weight bold))))
   `(show-paren-mismatch ((t (:foreground ,fg :background ,red :weight bold))))
   `(isearch            ((t (:foreground ,bg :background ,orange :weight bold))))
   `(lazy-highlight     ((t (:foreground ,bg :background ,yellow))))
   `(match              ((t (:foreground ,bg :background ,yellow))))
   `(isearch-fail       ((t (:foreground ,fg :background ,red))))
   `(evil-ex-lazy-highlight ((t (:foreground ,bg :background ,yellow))))
   `(evil-ex-substitute-matches ((t (:foreground ,bg :background ,red :strike-through t))))
   `(evil-ex-substitute-replacement ((t (:foreground ,bg :background ,green :underline t))))

   ;; --- popup / tamamlama ---
   `(completions-common-part ((t (:foreground ,orange :weight bold))))
   `(completions-first-difference ((t (:foreground ,red :weight bold))))
   `(completions-annotations ((t (:foreground ,gray :slant italic))))
   `(corfu-default      ((t (:foreground ,fg :background ,bg-light))))
   `(corfu-current      ((t (:foreground ,bg :background ,orange))))
   `(corfu-border       ((t (:background ,gray))))
   `(corfu-bar          ((t (:background ,gray))))
   `(corfu-annotations  ((t (:foreground ,gray :slant italic))))
   `(company-tooltip            ((t (:foreground ,fg :background ,bg-light))))
   `(company-tooltip-selection  ((t (:foreground ,bg :background ,orange))))
   `(company-tooltip-common     ((t (:foreground ,orange :weight bold))))
   `(company-tooltip-annotation ((t (:foreground ,cyan))))
   `(company-scrollbar-bg       ((t (:background ,bg-dark))))
   `(company-scrollbar-fg       ((t (:background ,gray))))
   `(tooltip            ((t (:foreground ,fg :background ,bg-light))))
   `(popup-face         ((t (:foreground ,fg :background ,bg-light))))
   `(popup-menu-selection-face ((t (:foreground ,bg :background ,orange))))

   ;; --- vertico / orderless / consult ---
   `(vertico-current    ((t (:background ,sel :weight bold))))
   `(vertico-group-title ((t (:foreground ,purple :weight bold))))
   `(vertico-group-separator ((t (:foreground ,gray-dk :strike-through t))))
   `(orderless-match-face-0 ((t (:foreground ,orange :weight bold))))
   `(orderless-match-face-1 ((t (:foreground ,purple :weight bold))))
   `(orderless-match-face-2 ((t (:foreground ,green :weight bold))))
   `(orderless-match-face-3 ((t (:foreground ,cyan :weight bold))))
   `(marginalia-key     ((t (:foreground ,orange))))
   `(marginalia-type    ((t (:foreground ,cyan :slant italic))))
   `(marginalia-file-priv-dir ((t (:foreground ,cyan))))
   `(consult-file       ((t (:foreground ,cyan))))
   `(consult-line-number ((t (:foreground ,gray))))
   `(consult-help       ((t (:foreground ,gray))))

   ;; --- highlight-* helpers ---
   `(highlight-numbers-number ((t (:foreground ,purple :weight bold))))
   `(highlight-quoted-symbol  ((t (:foreground ,purple :weight bold))))
   `(highlight-quoted-quote   ((t (:foreground ,red :weight bold))))
   `(hl-todo            ((t (:foreground ,yellow :weight bold))))
   `(rainbow-delimiters-depth-1-face ((t (:foreground ,red :weight bold))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,orange :weight bold))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,yellow :weight bold))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,green :weight bold))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,cyan :weight bold))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,purple :weight bold))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,red :weight bold))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,orange :weight bold))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground ,yellow :weight bold))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground ,red :background ,bg-lt2 :weight bold))))

   ;; --- modeline ---
   `(mode-line          ((t (:foreground ,fg :background ,ml-bg :box nil))))
   `(mode-line-inactive ((t (:foreground ,gray :background ,bg-dark :box nil))))
   `(mode-line-buffer-id ((t (:foreground ,green :weight bold))))
   `(mode-line-emphasis  ((t (:foreground ,orange :weight bold))))
   `(mode-line-highlight ((t (:foreground ,bg :background ,orange))))

   ;; --- header / tab-line / centaur-tabs ---
   `(header-line        ((t (:foreground ,gray :background ,bg-dark :box nil :underline nil :overline nil))))
   `(tab-line           ((t (:foreground ,gray :background ,bg-dark :box nil :underline nil :overline nil :height 0.9))))
   `(tab-bar            ((t (:foreground ,gray :background ,bg-dark :box nil))))
   `(tab-bar-tab        ((t (:foreground ,fg :background ,bg-lt2 :weight bold :box nil))))
   `(tab-bar-tab-inactive ((t (:foreground ,gray :background ,bg-dark :box nil))))
   `(centaur-tabs-default
     ((t (:background ,bg-dark :foreground ,bg-dark :box nil))))
   `(centaur-tabs-unselected
     ((t (:background ,bg-dark :foreground ,gray :box nil :height 0.9))))
   `(centaur-tabs-selected
     ((t (:background ,bg-lt2 :foreground ,fg :weight bold :box nil :height 0.9))))
   `(centaur-tabs-unselected-modified
     ((t (:background ,bg-dark :foreground ,orange :box nil :height 0.9))))
   `(centaur-tabs-selected-modified
     ((t (:background ,bg-lt2 :foreground ,orange :weight bold :box nil :height 0.9))))
   `(centaur-tabs-close-unselected
     ((t (:inherit centaur-tabs-unselected :foreground ,gray-dk))))
   `(centaur-tabs-close-selected
     ((t (:inherit centaur-tabs-selected :foreground ,gray-lt))))
   `(centaur-tabs-modified-marker-selected
     ((t (:inherit centaur-tabs-selected :foreground ,orange))))
   `(centaur-tabs-modified-marker-unselected
     ((t (:inherit centaur-tabs-unselected :foreground ,orange))))
   `(centaur-tabs-active-bar-face
     ((t (:background ,orange))))

   ;; --- diff / git / magit ---
   `(diff-added         ((t (:foreground ,green :background ,bg))))
   `(diff-removed       ((t (:foreground ,red :background ,bg))))
   `(diff-changed       ((t (:foreground ,yellow :background ,bg))))
   `(diff-header        ((t (:foreground ,cyan :background ,bg-dark))))
   `(diff-file-header   ((t (:foreground ,purple :weight bold :background ,bg-dark))))
   `(diff-hunk-header   ((t (:foreground ,orange :background ,bg-light))))
   `(diff-refine-added  ((t (:foreground ,green :background ,bg-lt2 :weight bold))))
   `(diff-refine-removed ((t (:foreground ,red :background ,bg-lt2 :weight bold))))
   `(diff-hl-change     ((t (:foreground ,yellow :background ,yellow))))
   `(diff-hl-insert     ((t (:foreground ,green :background ,green))))
   `(diff-hl-delete     ((t (:foreground ,red :background ,red))))
   `(magit-section-heading ((t (:foreground ,red :weight bold))))
   `(magit-section-highlight ((t (:background ,bg-light))))
   `(magit-branch-local  ((t (:foreground ,green :weight bold))))
   `(magit-branch-remote ((t (:foreground ,cyan :weight bold))))
   `(magit-branch-current ((t (:foreground ,green :box t :weight bold))))
   `(magit-hash          ((t (:foreground ,gray))))
   `(magit-tag           ((t (:foreground ,orange :weight bold))))
   `(magit-filename      ((t (:foreground ,fg))))
   `(magit-diff-added    ((t (:foreground ,green :background ,bg))))
   `(magit-diff-removed  ((t (:foreground ,red :background ,bg))))
   `(magit-diff-context  ((t (:foreground ,gray))))
   `(magit-diff-hunk-heading ((t (:foreground ,fg :background ,bg-light))))
   `(magit-diff-hunk-heading-highlight ((t (:foreground ,fg :background ,bg-lt2))))
   `(magit-log-author    ((t (:foreground ,orange))))
   `(magit-log-date      ((t (:foreground ,gray))))
   `(git-commit-summary  ((t (:foreground ,green :weight bold))))
   `(git-commit-overlong-summary ((t (:foreground ,red :weight bold))))
   `(git-commit-comment-heading ((t (:foreground ,purple :weight bold))))

   ;; --- flycheck / diagnostics ---
   `(flycheck-error     ((t (:underline (:style wave :color ,red)))))
   `(flycheck-warning   ((t (:underline (:style wave :color ,orange)))))
   `(flycheck-info      ((t (:underline (:style wave :color ,cyan)))))
   `(flycheck-fringe-error ((t (:foreground ,red))))
   `(flycheck-fringe-warning ((t (:foreground ,orange))))
   `(flycheck-fringe-info ((t (:foreground ,cyan))))
   `(flymake-error      ((t (:underline (:style wave :color ,red)))))
   `(flymake-warning    ((t (:underline (:style wave :color ,orange)))))
   `(flymake-note       ((t (:underline (:style wave :color ,cyan)))))

   ;; --- LSP (semantic tokens genelde kapalı; hover/ref yüzleri) ---
   `(lsp-face-highlight-textual   ((t (:background ,bg-lt2))))
   `(lsp-face-highlight-read      ((t (:background ,bg-lt2 :underline t))))
   `(lsp-face-highlight-write     ((t (:background ,bg-lt2 :weight bold))))
   `(lsp-ui-doc-background        ((t (:background ,bg-dark))))
   `(lsp-ui-doc-header            ((t (:foreground ,red :weight bold :background ,bg-dark))))
   `(lsp-ui-sideline-code-action  ((t (:foreground ,yellow))))
   `(lsp-ui-sideline-current-symbol ((t (:foreground ,orange :weight bold))))
   `(lsp-ui-sideline-symbol       ((t (:foreground ,gray))))
   `(lsp-ui-sideline-symbol-info  ((t (:foreground ,gray :slant italic))))
   `(lsp-inlay-hint-face          ((t (:foreground ,gray :background ,bg :slant italic :height 0.9))))
   `(eldoc-highlight-function-argument ((t (:foreground ,orange :weight bold :underline t))))

   ;; --- org ---
   `(org-level-1        ((t (:foreground ,red :weight bold :height 1.2))))
   `(org-level-2        ((t (:foreground ,orange :weight bold :height 1.1))))
   `(org-level-3        ((t (:foreground ,yellow :weight bold))))
   `(org-level-4        ((t (:foreground ,green :weight bold))))
   `(org-level-5        ((t (:foreground ,cyan :weight bold))))
   `(org-level-6        ((t (:foreground ,purple :weight bold))))
   `(org-level-7        ((t (:foreground ,red :weight bold))))
   `(org-level-8        ((t (:foreground ,orange :weight bold))))
   `(org-document-title ((t (:foreground ,purple :weight bold :height 1.3))))
   `(org-document-info  ((t (:foreground ,cyan))))
   `(org-meta-line      ((t (:foreground ,gray :slant italic))))
   `(org-code           ((t (:foreground ,yellow :background ,bg-dark))))
   `(org-verbatim       ((t (:foreground ,orange))))
   `(org-block          ((t (:foreground ,fg :background ,bg-dark))))
   `(org-block-begin-line ((t (:foreground ,gray :background ,bg-dark :slant italic))))
   `(org-block-end-line ((t (:foreground ,gray :background ,bg-dark :slant italic))))
   `(org-link           ((t (:foreground ,purple :underline t))))
   `(org-todo           ((t (:foreground ,red :weight bold))))
   `(org-done           ((t (:foreground ,green :weight bold))))
   `(org-headline-done  ((t (:foreground ,gray :strike-through t))))
   `(org-table          ((t (:foreground ,cyan))))
   `(org-date           ((t (:foreground ,purple :underline t))))
   `(org-tag            ((t (:foreground ,gray :weight bold))))
   `(org-checkbox       ((t (:foreground ,orange :weight bold))))
   `(org-special-keyword ((t (:foreground ,gray :weight bold))))
   `(org-drawer         ((t (:foreground ,gray))))
   `(org-ellipsis       ((t (:foreground ,gray))))

   ;; --- markdown ---
   `(markdown-header-face           ((t (:foreground ,red :weight bold))))
   `(markdown-header-face-1         ((t (:foreground ,red :weight bold :height 1.2))))
   `(markdown-header-face-2         ((t (:foreground ,orange :weight bold :height 1.1))))
   `(markdown-header-face-3         ((t (:foreground ,yellow :weight bold))))
   `(markdown-header-face-4         ((t (:foreground ,green :weight bold))))
   `(markdown-header-delimiter-face ((t (:foreground ,red :weight bold))))
   `(markdown-code-face             ((t (:foreground ,yellow :background ,bg-dark))))
   `(markdown-inline-code-face      ((t (:foreground ,yellow))))
   `(markdown-pre-face              ((t (:foreground ,yellow :background ,bg-dark))))
   `(markdown-language-keyword-face ((t (:foreground ,cyan :weight bold))))
   `(markdown-link-face             ((t (:foreground ,purple :underline t))))
   `(markdown-url-face              ((t (:foreground ,gray :underline t))))
   `(markdown-bold-face             ((t (:foreground ,fg :weight bold))))
   `(markdown-italic-face           ((t (:foreground ,fg :slant italic))))
   `(markdown-list-face             ((t (:foreground ,red :weight bold))))
   `(markdown-markup-face           ((t (:foreground ,gray))))
   `(markdown-blockquote-face       ((t (:foreground ,gray :slant italic))))

   ;; --- web-mode / html / css / js (nvim HTML*/@tag eşlemesi) ---
   `(web-mode-html-tag-face            ((t (:foreground ,orange :weight bold))))
   `(web-mode-html-tag-bracket-face    ((t (:foreground ,gray-lt :weight bold))))
   `(web-mode-html-attr-name-face      ((t (:foreground ,green :weight bold))))
   `(web-mode-html-attr-value-face     ((t (:foreground ,yellow :weight bold))))
   `(web-mode-html-attr-equal-face     ((t (:foreground ,gray-lt))))
   `(web-mode-doctype-face             ((t (:foreground ,gray :slant italic))))
   `(web-mode-comment-face             ((t (:foreground "#ffffff" :slant italic))))
   `(web-mode-string-face              ((t (:foreground ,yellow :weight bold))))
   `(web-mode-keyword-face             ((t (:foreground ,red :weight bold))))
   `(web-mode-type-face                ((t (:foreground ,cyan :slant italic :weight bold))))
   `(web-mode-function-name-face       ((t (:foreground ,green :weight bold))))
   `(web-mode-function-call-face       ((t (:foreground ,green :weight bold))))
   `(web-mode-variable-name-face       ((t (:foreground ,orange :weight bold))))
   `(web-mode-constant-face            ((t (:foreground ,purple :weight bold))))
   `(web-mode-builtin-face             ((t (:foreground ,cyan :weight bold))))
   `(web-mode-preprocessor-face        ((t (:foreground ,red :slant italic :weight bold))))
   `(web-mode-css-selector-face        ((t (:foreground ,red :weight bold))))
   `(web-mode-css-property-name-face   ((t (:foreground ,cyan :weight bold))))
   `(web-mode-css-string-face          ((t (:foreground ,yellow :weight bold))))
   `(web-mode-css-color-face           ((t (:foreground ,purple :weight bold))))
   `(web-mode-css-function-face        ((t (:foreground ,green :weight bold))))
   `(web-mode-symbol-face              ((t (:foreground ,orange :weight bold))))
   `(web-mode-block-delimiter-face     ((t (:foreground ,red :weight bold))))
   `(web-mode-block-control-face       ((t (:foreground ,red :weight bold))))
   `(web-mode-json-key-face            ((t (:foreground ,cyan :weight bold))))
   `(web-mode-json-string-face         ((t (:foreground ,yellow :weight bold))))
   `(css-selector       ((t (:foreground ,red :weight bold))))
   `(css-property       ((t (:foreground ,cyan :weight bold))))
   `(css-proprietary-property ((t (:foreground ,orange :weight bold))))
   `(nxml-element-local-name ((t (:foreground ,orange :weight bold))))
   `(nxml-attribute-local-name ((t (:foreground ,green :weight bold))))
   `(nxml-attribute-value ((t (:foreground ,yellow :weight bold))))
   `(nxml-tag-delimiter ((t (:foreground ,gray-lt))))
   `(nxml-comment-content ((t (:foreground "#ffffff" :slant italic))))

   ;; --- rust / go / python (mode-specific, treesit de font-lock kullanır) ---
   `(rustic-string-interpolation-face ((t (:foreground ,orange :weight bold))))
   `(rust-question-mark ((t (:foreground ,red :weight bold))))
   `(rust-string-interpolation ((t (:foreground ,orange :weight bold))))
   `(rust-builtin-formatting-macro ((t (:foreground ,cyan :weight bold))))
   `(go-ts-mode-error-call-face ((t (:foreground ,red :weight bold))))
   `(go-ts-mode-error-type-face ((t (:foreground ,red :weight bold))))
   `(python-decorator-face ((t (:foreground ,orange :weight bold))))
   `(python-info-variable-name-face ((t (:foreground ,orange :weight bold))))

   ;; --- sh / conf / yaml / json / toml ---
   `(sh-quoted-exec     ((t (:foreground ,green :weight bold))))
   `(sh-heredoc         ((t (:foreground ,yellow :weight bold))))
   `(sh-escaped-newline ((t (:foreground ,orange))))
   `(conf-keyword-face  ((t (:foreground ,red :weight bold))))
   `(conf-variable-face ((t (:foreground ,orange :weight bold))))
   `(yaml-tab-face      ((t (:background ,red))))
   `(json-mode-object-name-face ((t (:foreground ,cyan :weight bold))))

   ;; --- treemacs / dired / dirvish ---
   `(treemacs-directory-face     ((t (:foreground ,cyan :weight bold))))
   `(treemacs-root-face          ((t (:foreground ,purple :weight bold :height 1.1))))
   `(treemacs-file-face          ((t (:foreground ,fg))))
   `(treemacs-git-modified-face  ((t (:foreground ,orange))))
   `(treemacs-git-untracked-face ((t (:foreground ,green))))
   `(treemacs-git-added-face     ((t (:foreground ,green))))
   `(treemacs-git-conflict-face  ((t (:foreground ,red))))
   `(treemacs-git-ignored-face   ((t (:foreground ,gray))))
   `(dired-directory    ((t (:foreground ,cyan :weight bold))))
   `(dired-symlink      ((t (:foreground ,cyan :slant italic))))
   `(dired-header       ((t (:foreground ,purple :weight bold))))
   `(dired-marked       ((t (:foreground ,orange :weight bold))))
   `(dired-flagged      ((t (:foreground ,red :weight bold))))
   `(dired-ignored      ((t (:foreground ,gray))))
   `(dired-perm-write   ((t (:foreground ,red))))
   `(diredfl-dir-name   ((t (:foreground ,cyan :weight bold))))
   `(diredfl-file-name  ((t (:foreground ,fg))))
   `(diredfl-file-suffix ((t (:foreground ,gray))))
   `(diredfl-exec-priv  ((t (:foreground ,green))))
   `(diredfl-read-priv  ((t (:foreground ,yellow))))
   `(diredfl-write-priv ((t (:foreground ,red))))
   `(diredfl-date-time  ((t (:foreground ,purple))))
   `(diredfl-number     ((t (:foreground ,purple))))
   `(diredfl-dir-heading ((t (:foreground ,purple :weight bold))))

   ;; --- eshell / term / vterm / ansi ---
   `(eshell-prompt      ((t (:foreground ,green :weight bold))))
   `(eshell-ls-directory ((t (:foreground ,cyan :weight bold))))
   `(eshell-ls-executable ((t (:foreground ,green :weight bold))))
   `(eshell-ls-symlink  ((t (:foreground ,cyan :slant italic))))
   `(eshell-ls-archive  ((t (:foreground ,purple :weight bold))))
   `(eshell-ls-backup   ((t (:foreground ,gray))))
   `(eshell-ls-clutter  ((t (:foreground ,red))))
   `(eshell-ls-missing  ((t (:foreground ,red :weight bold))))
   `(eshell-ls-product  ((t (:foreground ,orange))))
   `(eshell-ls-readonly ((t (:foreground ,yellow))))
   `(eshell-ls-special  ((t (:foreground ,orange :weight bold))))
   `(eshell-ls-unreadable ((t (:foreground ,gray))))
   `(comint-highlight-prompt ((t (:foreground ,green :weight bold))))
   `(comint-highlight-input  ((t (:foreground ,fg :weight bold))))
   `(term-color-black   ((t (:foreground ,bg-dark :background ,bg-dark))))
   `(term-color-red     ((t (:foreground ,red :background ,red))))
   `(term-color-green   ((t (:foreground ,green :background ,green))))
   `(term-color-yellow  ((t (:foreground ,yellow :background ,yellow))))
   `(term-color-blue    ((t (:foreground ,cyan :background ,cyan))))
   `(term-color-magenta ((t (:foreground ,purple :background ,purple))))
   `(term-color-cyan    ((t (:foreground ,cyan :background ,cyan))))
   `(term-color-white   ((t (:foreground ,fg :background ,fg))))
   `(ansi-color-black   ((t (:foreground ,bg-dark :background ,bg-dark))))
   `(ansi-color-red     ((t (:foreground ,red :background ,red))))
   `(ansi-color-green   ((t (:foreground ,green :background ,green))))
   `(ansi-color-yellow  ((t (:foreground ,yellow :background ,yellow))))
   `(ansi-color-blue    ((t (:foreground ,cyan :background ,cyan))))
   `(ansi-color-magenta ((t (:foreground ,purple :background ,purple))))
   `(ansi-color-cyan    ((t (:foreground ,cyan :background ,cyan))))
   `(ansi-color-white   ((t (:foreground ,fg :background ,fg))))
   `(ansi-color-bright-black   ((t (:foreground ,gray :background ,gray))))
   `(ansi-color-bright-red     ((t (:foreground ,red :background ,red))))
   `(ansi-color-bright-green   ((t (:foreground ,green :background ,green))))
   `(ansi-color-bright-yellow  ((t (:foreground ,yellow :background ,yellow))))
   `(ansi-color-bright-blue    ((t (:foreground ,cyan :background ,cyan))))
   `(ansi-color-bright-magenta ((t (:foreground ,purple :background ,purple))))
   `(ansi-color-bright-cyan    ((t (:foreground ,cyan :background ,cyan))))
   `(ansi-color-bright-white   ((t (:foreground ,fg :background ,fg))))

   ;; --- which-key / help / elisp ---
   `(which-key-key-face              ((t (:foreground ,orange :weight bold))))
   `(which-key-separator-face        ((t (:foreground ,gray))))
   `(which-key-command-description-face ((t (:foreground ,fg))))
   `(which-key-group-description-face ((t (:foreground ,purple))))
   `(help-key-binding ((t (:foreground ,orange :background ,bg-dark :box (:line-width -1 :color ,gray-dk)))))
   `(helpful-heading  ((t (:foreground ,purple :weight bold :height 1.1))))
   `(outline-1        ((t (:foreground ,red :weight bold))))
   `(outline-2        ((t (:foreground ,orange :weight bold))))
   `(outline-3        ((t (:foreground ,yellow :weight bold))))
   `(outline-4        ((t (:foreground ,green :weight bold))))
   `(outline-5        ((t (:foreground ,cyan :weight bold))))
   `(outline-6        ((t (:foreground ,purple :weight bold))))

   ;; --- ivy-free / misc doom ---
   `(doom-modeline-buffer-file      ((t (:foreground ,fg :weight bold))))
   `(doom-modeline-buffer-modified  ((t (:foreground ,orange :weight bold))))
   `(doom-modeline-buffer-path      ((t (:foreground ,cyan :weight bold))))
   `(doom-modeline-project-dir      ((t (:foreground ,green :weight bold))))
   `(doom-modeline-info             ((t (:foreground ,green))))
   `(doom-modeline-warning          ((t (:foreground ,orange))))
   `(doom-modeline-urgent           ((t (:foreground ,red))))
   `(doom-modeline-bar              ((t (:background ,orange))))
   `(doom-modeline-panel            ((t (:foreground ,bg :background ,orange :weight bold))))
   `(solaire-default-face           ((t (:background ,bg-dark :foreground ,fg))))
   `(solaire-hl-line-face           ((t (:background ,hl))))
   `(solaire-mode-line-face         ((t (:background ,ml-bg :foreground ,fg))))
   `(solaire-mode-line-inactive-face ((t (:background ,bg-dark :foreground ,gray))))

   ;; --- widget / custom ---
   `(widget-field       ((t (:foreground ,fg :background ,bg-light :box (:line-width 1 :color ,gray-dk)))))
   `(custom-button      ((t (:foreground ,bg :background ,gray-lt :box (:line-width 1 :style released-button)))))
   `(custom-variable-tag ((t (:foreground ,cyan :weight bold))))
   `(custom-state       ((t (:foreground ,green))))

   ;; --- explorer: dirvish yan panel / treemacs / dired ------------------------
   ;; Monokai yapısı (dizin=cyan, dosya=fg, git=yeşil/amber/pembe), GITS neon ton.
   ;; Yan paneldeki imleç satırı teal HUD şeridi; ağaç kılavuzu zeminle aynı aile.
   `(dirvish-hl-line            ((t (:background "#203b53" :foreground "#e6ffff" :weight bold :extend t))))
   `(dirvish-hl-line-inactive   ((t (:background ,hl :extend t))))
   `(dirvish-inactive           ((t (:foreground ,gray-dk))))
   `(dirvish-subtree-state      ((t (:foreground ,cursor :weight bold))))
   `(dirvish-subtree-guide      ((t (:foreground ,gray-dk))))
   `(dirvish-collapse-dir-face       ((t (:foreground ,cyan :weight bold))))
   `(dirvish-collapse-empty-dir-face ((t (:foreground ,gray))))
   `(dirvish-collapse-file-face      ((t (:foreground ,gray-lt))))
   `(dirvish-free-space         ((t (:foreground ,gray))))
   `(dirvish-file-link-number   ((t (:foreground ,purple))))
   `(dirvish-file-user-id       ((t (:foreground ,gray-lt))))
   `(dirvish-file-group-id      ((t (:foreground ,gray))))
   `(dirvish-file-time          ((t (:foreground ,gray :slant italic))))
   `(dirvish-file-size          ((t (:foreground ,purple))))
   `(dirvish-file-modes         ((t (:foreground ,gray-lt))))
   `(dirvish-file-inode-number  ((t (:foreground ,gray))))
   `(dirvish-file-device-number ((t (:foreground ,gray))))
   `(dirvish-media-info-heading      ((t (:foreground ,purple :weight bold))))
   `(dirvish-media-info-property-key ((t (:foreground ,cyan :weight bold))))
   `(dirvish-proc-running       ((t (:foreground ,orange))))
   `(dirvish-proc-finished      ((t (:foreground ,green))))
   `(dirvish-proc-failed        ((t (:foreground ,red))))
   `(dirvish-git-commit-message-face ((t (:foreground ,gray :slant italic))))
   `(dirvish-vc-edited-state       ((t (:foreground ,orange :weight bold))))
   `(dirvish-vc-added-state        ((t (:foreground ,green :weight bold))))
   `(dirvish-vc-removed-state      ((t (:foreground ,red :weight bold))))
   `(dirvish-vc-missing-state      ((t (:foreground ,red :weight bold))))
   `(dirvish-vc-conflict-state     ((t (:foreground ,red :weight bold))))
   `(dirvish-vc-locked-state       ((t (:foreground ,purple :weight bold))))
   `(dirvish-vc-needs-update-state ((t (:foreground ,yellow :weight bold))))
   `(dirvish-vc-needs-merge-face   ((t (:background "#3a1220"))))
   `(dirvish-vc-unregistered-face  ((t (:foreground ,gray))))
   `(dirvish-narrow-match-face-0 ((t (:foreground ,cursor :weight bold))))
   `(dirvish-narrow-match-face-1 ((t (:foreground ,red :weight bold))))
   `(dirvish-narrow-match-face-2 ((t (:foreground ,orange :weight bold))))
   `(dirvish-narrow-match-face-3 ((t (:foreground ,green :weight bold))))
   `(dirvish-narrow-split        ((t (:foreground ,gray-dk))))
   `(dirvish-emerge-group-title  ((t (:foreground ,purple :weight bold))))

   `(treemacs-hl-line-face            ((t (:background "#203b53" :foreground "#e6ffff" :weight bold :extend t))))
   `(treemacs-window-background-face  ((t (:background ,bg))))
   `(treemacs-directory-collapsed-face ((t (:foreground ,cyan))))
   `(treemacs-tags-face               ((t (:foreground ,orange))))
   `(treemacs-header-button-face      ((t (:foreground ,purple :weight bold))))
   `(treemacs-help-title-face         ((t (:foreground ,purple :weight bold))))
   `(treemacs-help-column-face        ((t (:foreground ,orange :weight bold))))
   `(treemacs-marked-file-face        ((t (:foreground ,bg :background ,orange :weight bold))))
   `(treemacs-git-renamed-face        ((t (:foreground ,purple :slant italic))))
   `(treemacs-git-unmodified-face     ((t (:foreground ,fg))))
   `(treemacs-git-commit-diff-face    ((t (:foreground ,red))))
   `(treemacs-async-loading-face      ((t (:foreground ,cursor :slant italic))))
   `(treemacs-fringe-indicator-face   ((t (:foreground ,cursor))))
   `(treemacs-peek-mode-indicator-face ((t (:foreground ,cursor))))
   `(treemacs-on-success-pulse-face   ((t (:foreground ,bg :background ,green :weight bold))))
   `(treemacs-on-failure-pulse-face   ((t (:foreground ,bg :background ,red :weight bold))))
   `(treemacs-root-remote-face        ((t (:foreground ,cyan :weight bold :height 1.1))))
   `(treemacs-root-unreadable-face    ((t (:foreground ,red :weight bold :height 1.1))))
   `(treemacs-root-remote-disconnected-face ((t (:foreground ,orange :weight bold :height 1.1))))
   `(treemacs-root-remote-unreadable-face   ((t (:foreground ,red :weight bold :height 1.1))))
   `(treemacs-term-node-face          ((t (:foreground ,cyan :weight bold))))

   `(dired-broken-symlink ((t (:foreground ,red :weight bold))))
   `(dired-special        ((t (:foreground ,purple))))
   `(dired-set-id         ((t (:foreground ,orange))))
   `(dired-warning        ((t (:foreground ,orange :weight bold))))
   `(dired-mark           ((t (:foreground ,cursor :weight bold))))
   `(diredfl-symlink              ((t (:foreground ,cyan :slant italic))))
   `(diredfl-dir-priv             ((t (:foreground ,cyan :weight bold))))
   `(diredfl-link-priv            ((t (:foreground ,cyan))))
   `(diredfl-other-priv           ((t (:foreground ,purple))))
   `(diredfl-rare-priv            ((t (:foreground ,red :weight bold))))
   `(diredfl-no-priv              ((t (:foreground ,gray-dk))))
   `(diredfl-executable-tag       ((t (:foreground ,green :weight bold))))
   `(diredfl-compressed-file-name   ((t (:foreground ,purple))))
   `(diredfl-compressed-file-suffix ((t (:foreground ,purple :weight bold))))
   `(diredfl-ignored-file-name    ((t (:foreground ,gray))))
   `(diredfl-deletion             ((t (:foreground ,red :background ,bg-light :weight bold))))
   `(diredfl-deletion-file-name   ((t (:foreground ,red :weight bold))))
   `(diredfl-flag-mark            ((t (:foreground ,bg :background ,orange :weight bold))))
   `(diredfl-flag-mark-line       ((t (:background ,hl :extend t))))
   `(diredfl-autofile-name        ((t (:background ,bg-light))))
   `(diredfl-tagged-autofile-name ((t (:foreground ,yellow :background ,bg-light))))

   ;; --- nerd-icons: ikon paleti (ağaç + dired + modeline + dashboard) ---------
   ;; Paket kendi pastel paletiyle gelir (#8fd7f4, #aa759f gibi); GITS neonuna
   ;; çekildi, ton aileleri korundu → ikonlar hâlâ ayrışıyor ama temadan taşmıyor.
   `(nerd-icons-red      ((t (:foreground ,red))))
   `(nerd-icons-red-alt  ((t (:foreground ,red))))
   `(nerd-icons-lred     ((t (:foreground "#ff6fa3"))))
   `(nerd-icons-dred     ((t (:foreground "#d62a63"))))
   `(nerd-icons-pink     ((t (:foreground "#ff6fc0"))))
   `(nerd-icons-lpink    ((t (:foreground "#ff9ad6"))))
   `(nerd-icons-dpink    ((t (:foreground "#e0399b"))))
   `(nerd-icons-maroon   ((t (:foreground "#d1568f"))))
   `(nerd-icons-lmaroon  ((t (:foreground "#ff85b8"))))
   `(nerd-icons-dmaroon  ((t (:foreground "#a33a6b"))))
   `(nerd-icons-orange   ((t (:foreground ,orange))))
   `(nerd-icons-lorange  ((t (:foreground "#ff9e3b"))))
   `(nerd-icons-dorange  ((t (:foreground "#e07c1a"))))
   `(nerd-icons-yellow   ((t (:foreground ,yellow))))
   `(nerd-icons-lyellow  ((t (:foreground "#ccf07f"))))
   `(nerd-icons-dyellow  ((t (:foreground "#8fc22f"))))
   `(nerd-icons-green    ((t (:foreground ,green))))
   `(nerd-icons-lgreen   ((t (:foreground "#6bf0c2"))))
   `(nerd-icons-dgreen   ((t (:foreground "#1fbd86"))))
   `(nerd-icons-cyan     ((t (:foreground ,cursor))))
   `(nerd-icons-cyan-alt ((t (:foreground ,cursor))))
   `(nerd-icons-lcyan    ((t (:foreground "#66f7ee"))))
   `(nerd-icons-dcyan    ((t (:foreground "#00bdb1"))))
   `(nerd-icons-blue     ((t (:foreground ,cyan))))
   `(nerd-icons-blue-alt ((t (:foreground ,cyan))))
   `(nerd-icons-lblue    ((t (:foreground "#7adbff"))))
   `(nerd-icons-dblue    ((t (:foreground "#1f9ad6"))))
   `(nerd-icons-purple   ((t (:foreground ,purple))))
   `(nerd-icons-purple-alt ((t (:foreground ,purple))))
   `(nerd-icons-lpurple  ((t (:foreground "#cbb0ff"))))
   `(nerd-icons-dpurple  ((t (:foreground "#8a5cf0"))))
   `(nerd-icons-silver   ((t (:foreground ,gray))))
   `(nerd-icons-lsilver  ((t (:foreground "#93b3b3"))))
   `(nerd-icons-dsilver  ((t (:foreground "#4d6666"))))

   ;; --- vterm / transient / avy / embark / evil-goggles ------------------------
   `(vterm-color-black   ((t (:foreground "#0e1724" :background "#0e1724"))))
   `(vterm-color-red     ((t (:foreground "#ff3d81" :background "#ff3d81"))))
   `(vterm-color-green   ((t (:foreground "#a6e22e" :background "#a6e22e"))))
   `(vterm-color-yellow  ((t (:foreground "#ff9e3b" :background "#ff9e3b"))))
   `(vterm-color-blue    ((t (:foreground "#4fb3d4" :background "#4fb3d4"))))
   `(vterm-color-magenta ((t (:foreground "#996de0" :background "#996de0"))))
   `(vterm-color-cyan    ((t (:foreground "#00d5e0" :background "#00d5e0"))))
   `(vterm-color-white   ((t (:foreground "#a9c7c9" :background "#a9c7c9"))))
   `(vterm-color-bright-black   ((t (:foreground "#3f5f6a" :background "#3f5f6a"))))
   `(vterm-color-bright-red     ((t (:foreground "#ff6fa3" :background "#ff6fa3"))))
   `(vterm-color-bright-green   ((t (:foreground "#6ff5c8" :background "#6ff5c8"))))
   `(vterm-color-bright-yellow  ((t (:foreground "#aa82e8" :background "#aa82e8"))))
   `(vterm-color-bright-blue    ((t (:foreground "#4fb3d4" :background "#4fb3d4"))))
   `(vterm-color-bright-magenta ((t (:foreground "#cdb0ff" :background "#cdb0ff"))))
   `(vterm-color-bright-cyan    ((t (:foreground "#5cf2f5" :background "#5cf2f5"))))
   `(vterm-color-bright-white   ((t (:foreground "#e6ffff" :background "#e6ffff"))))
   `(vterm-color-underline      ((t (:underline t))))
   `(vterm-color-inverse-video  ((t (:inverse-video t))))
   `(transient-heading          ((t (:foreground ,purple :weight bold))))
   `(transient-key              ((t (:foreground ,orange :weight bold))))
   `(transient-key-stay         ((t (:foreground ,green :weight bold))))
   `(transient-key-exit         ((t (:foreground ,red :weight bold))))
   `(transient-key-return       ((t (:foreground ,yellow :weight bold))))
   `(transient-key-stack        ((t (:foreground ,cursor :weight bold))))
   `(transient-key-recurse      ((t (:foreground ,cyan :weight bold))))
   `(transient-key-noop         ((t (:foreground ,gray-dk))))
   `(transient-argument         ((t (:foreground ,cursor :weight bold))))
   `(transient-value            ((t (:foreground ,yellow))))
   `(transient-inactive-argument ((t (:foreground ,gray))))
   `(transient-inactive-value   ((t (:foreground ,gray))))
   `(transient-enabled-suffix   ((t (:foreground ,bg :background ,green :weight bold))))
   `(transient-disabled-suffix  ((t (:foreground ,bg :background ,red :weight bold))))
   `(transient-unreachable      ((t (:foreground ,gray-dk))))
   `(transient-unreachable-key  ((t (:foreground ,gray-dk))))
   `(transient-delimiter        ((t (:foreground ,gray-dk))))
   `(avy-lead-face   ((t (:foreground ,bg :background ,cursor :weight bold))))
   `(avy-lead-face-0 ((t (:foreground ,bg :background ,red :weight bold))))
   `(avy-lead-face-1 ((t (:foreground ,bg :background ,orange :weight bold))))
   `(avy-lead-face-2 ((t (:foreground ,bg :background ,purple :weight bold))))
   `(avy-background-face ((t (:foreground ,gray-dk))))
   `(avy-goto-char-timer-face ((t (:foreground ,bg :background ,yellow :weight bold))))
   `(embark-keybinding        ((t (:foreground ,orange :weight bold))))
   `(embark-keybinding-repeat ((t (:foreground ,cursor :weight bold))))
   `(embark-keymap            ((t (:foreground ,purple))))
   `(embark-target            ((t (:background ,sel :weight bold))))
   `(embark-selected          ((t (:foreground ,bg :background ,cursor :weight bold))))
   `(embark-collect-group-title ((t (:foreground ,purple :weight bold))))
   `(embark-collect-annotation  ((t (:foreground ,gray))))
   `(embark-verbose-indicator-title ((t (:foreground ,purple :weight bold))))
   `(embark-verbose-indicator-documentation ((t (:foreground ,gray))))
   `(evil-goggles-default-face  ((t (:background ,sel))))
   `(evil-goggles-yank-face     ((t (:background "#203b53"))))
   `(evil-goggles-delete-face   ((t (:background "#3a1220"))))
   `(evil-goggles-change-face   ((t (:background "#3d2a12"))))
   `(evil-goggles-paste-face    ((t (:background "#123a2c"))))
   `(evil-goggles-indent-face   ((t (:background ,bg-lt2))))
   `(evil-goggles-join-face     ((t (:background ,bg-lt2))))
   `(evil-goggles-commentary-face ((t (:background ,bg-lt2))))
   `(evil-goggles-nerd-commenter-face ((t (:background ,bg-lt2))))
   `(evil-goggles-surround-face ((t (:background ,bg-lt2))))
   `(evil-goggles-record-macro-face ((t (:background "#3a1220"))))
   `(ibuffer-locked-buffer ((t (:foreground ,red))))
   `(vi-tilde-fringe-face  ((t (:foreground ,gray-dk))))
   ))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'ghostty)
;;; ghostty-theme.el ends here
