;;; tugmonokai-theme.el --- TugMonokai Bold Edition -*- lexical-binding: t; -*-
;; nvim ~/.config/nvim/colors/tugmonokai.lua port'u (Emacs deftheme).
;; Treesit level-4 + web/org/magit yüzleri dahil — beyaz kalan syntax yok.

(deftheme tugmonokai "TugMonokai - Bold Edition (Monokai).")

;; Arka plan/UI paleti = nvim colors/tugmonokai.lua (bg/bg_dark/bg_light/
;; bg_lighter/selection/gray_dark/border) — birebir.  Eski doom-one zeminli
;; hali: tugmonokai-theme.el.doomone.bak
(let ((bg        "#1e1f1c")   ; nvim bg (Normal)
      (bg-dark   "#181915")   ; nvim bg_dark (NormalFloat, StatusLineNC, tab arka planı)
      (bg-light  "#2a2a2a")   ; nvim bg_light (CursorLine, Pmenu, StatusLine)
      (bg-lt2    "#333333")   ; nvim bg_lighter (MatchParen, seçili sekme)
      (ml-bg     "#2a2a2a")   ; nvim StatusLine / lualine b bölümü
      (fg        "#f8f8f2")
      (fg-dark   "#d4d4d4")
      (red       "#f92672")
      (orange    "#fd971f")
      (yellow    "#e6db74")
      (green     "#a6e22e")
      (cyan      "#66d9ef")
      (purple    "#ae81ff")
      (gray      "#75715e")
      (gray-lt   "#8f8f8f")
      (gray-dk   "#49483e")   ; nvim gray_dark (LineNr, WinSeparator)
      (cursor    "#fd971f")
      (sel       "#49483e")   ; nvim selection (Visual)
      (border    "#5c5c5c"))  ; nvim border
  (custom-theme-set-faces
   'tugmonokai
   ;; --- temel ---
   `(default            ((t (:background ,bg :foreground ,fg))))
   `(cursor             ((t (:background ,cursor))))
   `(region             ((t (:background ,sel))))
   `(secondary-selection ((t (:background ,bg-lt2))))
   `(highlight          ((t (:background ,sel))))
   `(hl-line            ((t (:background ,bg-light))))
   `(fringe             ((t (:background ,bg :foreground ,gray-dk))))
   `(line-number        ((t (:foreground ,gray-dk :background ,bg))))
   `(line-number-current-line ((t (:foreground ,orange :background ,bg :weight bold))))
   `(vertical-border    ((t (:foreground ,gray-dk))))
   `(window-divider     ((t (:foreground ,gray-dk))))
   `(window-divider-first-pixel ((t (:foreground ,gray-dk))))
   `(window-divider-last-pixel  ((t (:foreground ,gray-dk))))
   `(minibuffer-prompt  ((t (:foreground ,green :weight bold))))
   `(shadow             ((t (:foreground ,gray))))
   `(link               ((t (:foreground ,purple :underline t))))
   `(link-visited       ((t (:foreground ,purple :underline t :weight normal))))
   `(button             ((t (:foreground ,cyan :underline t))))
   `(error              ((t (:foreground ,red :weight bold))))
   `(warning            ((t (:foreground ,orange :weight bold))))
   `(success            ((t (:foreground ,green :weight bold))))
   `(escape-glyph       ((t (:foreground ,orange :weight bold))))
   `(homoglyph          ((t (:foreground ,orange :weight bold))))
   `(nobreak-space      ((t (:foreground ,gray :underline t))))
   `(trailing-whitespace ((t (:background ,red))))
   `(whitespace-space   ((t (:foreground ,gray-dk))))
   `(whitespace-tab     ((t (:foreground ,gray-dk))))
   `(whitespace-newline ((t (:foreground ,gray-dk))))
   `(fill-column-indicator ((t (:foreground ,gray-dk))))

   ;; --- söz dizimi: font-lock + treesit (level 4) ---
   ;; nvim Bold Edition: syntax face'ler bold.
   ;; nvim eşlemesi:
   ;;   keyword/op/preproc → red | string → yellow | fn → green
   ;;   type → cyan italic | const/number → purple | comment → gray
   ;;   property/param/member/attr/tag → orange | variable → fg
   `(font-lock-keyword-face          ((t (:foreground ,red :weight bold))))
   `(font-lock-comment-face          ((t (:foreground ,gray :slant italic :weight bold))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,gray :slant italic :weight bold))))
   `(font-lock-doc-face              ((t (:foreground ,gray :slant italic :weight bold))))
   `(font-lock-doc-markup-face       ((t (:foreground ,cyan :weight bold))))
   `(font-lock-string-face           ((t (:foreground ,yellow :weight bold))))
   `(font-lock-doc-string-face       ((t (:foreground ,yellow :weight bold)))) ; eski alias
   `(font-lock-function-name-face    ((t (:foreground ,green :weight bold))))
   `(font-lock-function-call-face    ((t (:foreground ,green :weight bold))))
   ;; nvim @variable = fg; @variable.parameter/member = orange
   ;; treesit çoğu param/def'i variable-name'e yazar → orange (daha renkli)
   `(font-lock-variable-name-face    ((t (:foreground ,orange :weight bold))))
   `(font-lock-variable-use-face     ((t (:foreground ,fg :weight bold))))
   `(font-lock-property-name-face    ((t (:foreground ,orange :weight bold))))
   `(font-lock-property-use-face     ((t (:foreground ,orange :weight bold))))
   `(font-lock-type-face             ((t (:foreground ,cyan :slant italic :weight bold))))
   `(font-lock-type-definition-face  ((t (:foreground ,cyan :weight bold))))
   `(font-lock-constant-face         ((t (:foreground ,purple :weight bold))))
   `(font-lock-number-face           ((t (:foreground ,purple :weight bold))))
   `(font-lock-builtin-face          ((t (:foreground ,cyan :weight bold))))
   `(font-lock-preprocessor-face     ((t (:foreground ,red :slant italic :weight bold))))
   `(font-lock-operator-face         ((t (:foreground ,red :weight bold))))
   `(font-lock-delimiter-face        ((t (:foreground ,gray-lt :weight bold))))
   `(font-lock-bracket-face          ((t (:foreground ,gray-lt :weight bold))))
   `(font-lock-punctuation-face      ((t (:foreground ,gray-lt :weight bold))))
   `(font-lock-misc-punctuation-face ((t (:foreground ,orange :weight bold))))
   `(font-lock-escape-face           ((t (:foreground ,orange :weight bold))))
   `(font-lock-negation-char-face    ((t (:foreground ,red :weight bold))))
   `(font-lock-warning-face          ((t (:foreground ,red :weight bold))))
   `(font-lock-regexp-face           ((t (:foreground ,yellow :weight bold))))
   `(font-lock-regexp-grouping-backslash  ((t (:foreground ,red :weight bold))))
   `(font-lock-regexp-grouping-construct  ((t (:foreground ,red :weight bold))))

   ;; --- arama / eşleşme ---
   `(show-paren-match   ((t (:foreground ,orange :background ,bg-lt2 :weight bold))))
   `(show-paren-mismatch ((t (:foreground ,fg :background ,red :weight bold))))
   `(isearch            ((t (:foreground ,bg :background ,orange :weight bold))))
   `(lazy-highlight     ((t (:foreground ,bg :background ,yellow))))
   `(match              ((t (:foreground ,bg :background ,yellow))))
   `(isearch-fail       ((t (:foreground ,fg :background ,red))))
   `(evil-ex-lazy-highlight ((t (:foreground ,bg :background ,yellow))))
   `(evil-ex-substitute-matches ((t (:foreground ,bg :background ,red :strike-through t))))
   `(evil-ex-substitute-replacement ((t (:foreground ,bg :background ,green :underline t))))

   ;; --- popup / tamamlama ---
   `(completions-common-part ((t (:foreground ,orange :weight bold))))
   `(completions-first-difference ((t (:foreground ,red :weight bold))))
   `(completions-annotations ((t (:foreground ,gray :slant italic))))
   `(corfu-default      ((t (:foreground ,fg :background ,bg-light))))
   `(corfu-current      ((t (:foreground ,bg :background ,orange))))
   `(corfu-border       ((t (:background ,gray))))
   `(corfu-bar          ((t (:background ,gray))))
   `(corfu-annotations  ((t (:foreground ,gray :slant italic))))
   `(company-tooltip            ((t (:foreground ,fg :background ,bg-light))))
   `(company-tooltip-selection  ((t (:foreground ,bg :background ,orange))))
   `(company-tooltip-common     ((t (:foreground ,orange :weight bold))))
   `(company-tooltip-annotation ((t (:foreground ,cyan))))
   `(company-scrollbar-bg       ((t (:background ,bg-dark))))
   `(company-scrollbar-fg       ((t (:background ,gray))))
   `(tooltip            ((t (:foreground ,fg :background ,bg-light))))
   `(popup-face         ((t (:foreground ,fg :background ,bg-light))))
   `(popup-menu-selection-face ((t (:foreground ,bg :background ,orange))))

   ;; --- vertico / orderless / consult ---
   `(vertico-current    ((t (:background ,sel :weight bold))))
   `(vertico-group-title ((t (:foreground ,purple :weight bold))))
   `(vertico-group-separator ((t (:foreground ,gray-dk :strike-through t))))
   `(orderless-match-face-0 ((t (:foreground ,orange :weight bold))))
   `(orderless-match-face-1 ((t (:foreground ,purple :weight bold))))
   `(orderless-match-face-2 ((t (:foreground ,green :weight bold))))
   `(orderless-match-face-3 ((t (:foreground ,cyan :weight bold))))
   `(marginalia-key     ((t (:foreground ,orange))))
   `(marginalia-type    ((t (:foreground ,cyan :slant italic))))
   `(marginalia-file-priv-dir ((t (:foreground ,cyan))))
   `(consult-file       ((t (:foreground ,cyan))))
   `(consult-line-number ((t (:foreground ,gray))))
   `(consult-help       ((t (:foreground ,gray))))

   ;; --- highlight-* helpers ---
   `(highlight-numbers-number ((t (:foreground ,purple :weight bold))))
   `(highlight-quoted-symbol  ((t (:foreground ,purple :weight bold))))
   `(highlight-quoted-quote   ((t (:foreground ,red :weight bold))))
   `(hl-todo            ((t (:foreground ,yellow :weight bold))))
   `(rainbow-delimiters-depth-1-face ((t (:foreground ,red :weight bold))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,orange :weight bold))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,yellow :weight bold))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,green :weight bold))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,cyan :weight bold))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,purple :weight bold))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,red :weight bold))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,orange :weight bold))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground ,yellow :weight bold))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground ,red :background ,bg-lt2 :weight bold))))

   ;; --- modeline ---
   `(mode-line          ((t (:foreground ,fg :background ,ml-bg :box nil))))
   `(mode-line-inactive ((t (:foreground ,gray :background ,bg-dark :box nil))))
   `(mode-line-buffer-id ((t (:foreground ,green :weight bold))))
   `(mode-line-emphasis  ((t (:foreground ,orange :weight bold))))
   `(mode-line-highlight ((t (:foreground ,bg :background ,orange))))

   ;; --- header / tab-line / centaur-tabs ---
   `(header-line        ((t (:foreground ,gray :background ,bg-dark :box nil :underline nil :overline nil))))
   `(tab-line           ((t (:foreground ,gray :background ,bg-dark :box nil :underline nil :overline nil :height 0.9))))
   `(tab-bar            ((t (:foreground ,gray :background ,bg-dark :box nil))))
   `(tab-bar-tab        ((t (:foreground ,fg :background ,bg-lt2 :weight bold :box nil))))
   `(tab-bar-tab-inactive ((t (:foreground ,gray :background ,bg-dark :box nil))))
   `(centaur-tabs-default
     ((t (:background ,bg-dark :foreground ,bg-dark :box nil))))
   `(centaur-tabs-unselected
     ((t (:background ,bg-dark :foreground ,gray :box nil :height 0.9))))
   `(centaur-tabs-selected
     ((t (:background ,bg-lt2 :foreground ,fg :weight bold :box nil :height 0.9))))
   `(centaur-tabs-unselected-modified
     ((t (:background ,bg-dark :foreground ,orange :box nil :height 0.9))))
   `(centaur-tabs-selected-modified
     ((t (:background ,bg-lt2 :foreground ,orange :weight bold :box nil :height 0.9))))
   `(centaur-tabs-close-unselected
     ((t (:inherit centaur-tabs-unselected :foreground ,gray-dk))))
   `(centaur-tabs-close-selected
     ((t (:inherit centaur-tabs-selected :foreground ,gray-lt))))
   `(centaur-tabs-modified-marker-selected
     ((t (:inherit centaur-tabs-selected :foreground ,orange))))
   `(centaur-tabs-modified-marker-unselected
     ((t (:inherit centaur-tabs-unselected :foreground ,orange))))
   `(centaur-tabs-active-bar-face
     ((t (:background ,orange))))

   ;; --- diff / git / magit ---
   `(diff-added         ((t (:foreground ,green :background ,bg))))
   `(diff-removed       ((t (:foreground ,red :background ,bg))))
   `(diff-changed       ((t (:foreground ,yellow :background ,bg))))
   `(diff-header        ((t (:foreground ,cyan :background ,bg-dark))))
   `(diff-file-header   ((t (:foreground ,purple :weight bold :background ,bg-dark))))
   `(diff-hunk-header   ((t (:foreground ,orange :background ,bg-light))))
   `(diff-refine-added  ((t (:foreground ,green :background ,bg-lt2 :weight bold))))
   `(diff-refine-removed ((t (:foreground ,red :background ,bg-lt2 :weight bold))))
   `(diff-hl-change     ((t (:foreground ,yellow :background ,yellow))))
   `(diff-hl-insert     ((t (:foreground ,green :background ,green))))
   `(diff-hl-delete     ((t (:foreground ,red :background ,red))))
   `(magit-section-heading ((t (:foreground ,red :weight bold))))
   `(magit-section-highlight ((t (:background ,bg-light))))
   `(magit-branch-local  ((t (:foreground ,green :weight bold))))
   `(magit-branch-remote ((t (:foreground ,cyan :weight bold))))
   `(magit-branch-current ((t (:foreground ,green :box t :weight bold))))
   `(magit-hash          ((t (:foreground ,gray))))
   `(magit-tag           ((t (:foreground ,orange :weight bold))))
   `(magit-filename      ((t (:foreground ,fg))))
   `(magit-diff-added    ((t (:foreground ,green :background ,bg))))
   `(magit-diff-removed  ((t (:foreground ,red :background ,bg))))
   `(magit-diff-context  ((t (:foreground ,gray))))
   `(magit-diff-hunk-heading ((t (:foreground ,fg :background ,bg-light))))
   `(magit-diff-hunk-heading-highlight ((t (:foreground ,fg :background ,bg-lt2))))
   `(magit-log-author    ((t (:foreground ,orange))))
   `(magit-log-date      ((t (:foreground ,gray))))
   `(git-commit-summary  ((t (:foreground ,green :weight bold))))
   `(git-commit-overlong-summary ((t (:foreground ,red :weight bold))))
   `(git-commit-comment-heading ((t (:foreground ,purple :weight bold))))

   ;; --- flycheck / diagnostics ---
   `(flycheck-error     ((t (:underline (:style wave :color ,red)))))
   `(flycheck-warning   ((t (:underline (:style wave :color ,orange)))))
   `(flycheck-info      ((t (:underline (:style wave :color ,cyan)))))
   `(flycheck-fringe-error ((t (:foreground ,red))))
   `(flycheck-fringe-warning ((t (:foreground ,orange))))
   `(flycheck-fringe-info ((t (:foreground ,cyan))))
   `(flymake-error      ((t (:underline (:style wave :color ,red)))))
   `(flymake-warning    ((t (:underline (:style wave :color ,orange)))))
   `(flymake-note       ((t (:underline (:style wave :color ,cyan)))))

   ;; --- LSP (semantic tokens genelde kapalı; hover/ref yüzleri) ---
   `(lsp-face-highlight-textual   ((t (:background ,bg-lt2))))
   `(lsp-face-highlight-read      ((t (:background ,bg-lt2 :underline t))))
   `(lsp-face-highlight-write     ((t (:background ,bg-lt2 :weight bold))))
   `(lsp-ui-doc-background        ((t (:background ,bg-dark))))
   `(lsp-ui-doc-header            ((t (:foreground ,red :weight bold :background ,bg-dark))))
   `(lsp-ui-sideline-code-action  ((t (:foreground ,yellow))))
   `(lsp-ui-sideline-current-symbol ((t (:foreground ,orange :weight bold))))
   `(lsp-ui-sideline-symbol       ((t (:foreground ,gray))))
   `(lsp-ui-sideline-symbol-info  ((t (:foreground ,gray :slant italic))))
   `(lsp-inlay-hint-face          ((t (:foreground ,gray :background ,bg :slant italic :height 0.9))))
   `(eldoc-highlight-function-argument ((t (:foreground ,orange :weight bold :underline t))))

   ;; --- org ---
   `(org-level-1        ((t (:foreground ,red :weight bold :height 1.2))))
   `(org-level-2        ((t (:foreground ,orange :weight bold :height 1.1))))
   `(org-level-3        ((t (:foreground ,yellow :weight bold))))
   `(org-level-4        ((t (:foreground ,green :weight bold))))
   `(org-level-5        ((t (:foreground ,cyan :weight bold))))
   `(org-level-6        ((t (:foreground ,purple :weight bold))))
   `(org-level-7        ((t (:foreground ,red :weight bold))))
   `(org-level-8        ((t (:foreground ,orange :weight bold))))
   `(org-document-title ((t (:foreground ,purple :weight bold :height 1.3))))
   `(org-document-info  ((t (:foreground ,cyan))))
   `(org-meta-line      ((t (:foreground ,gray :slant italic))))
   `(org-code           ((t (:foreground ,yellow :background ,bg-dark))))
   `(org-verbatim       ((t (:foreground ,orange))))
   `(org-block          ((t (:foreground ,fg :background ,bg-dark))))
   `(org-block-begin-line ((t (:foreground ,gray :background ,bg-dark :slant italic))))
   `(org-block-end-line ((t (:foreground ,gray :background ,bg-dark :slant italic))))
   `(org-link           ((t (:foreground ,purple :underline t))))
   `(org-todo           ((t (:foreground ,red :weight bold))))
   `(org-done           ((t (:foreground ,green :weight bold))))
   `(org-headline-done  ((t (:foreground ,gray :strike-through t))))
   `(org-table          ((t (:foreground ,cyan))))
   `(org-date           ((t (:foreground ,purple :underline t))))
   `(org-tag            ((t (:foreground ,gray :weight bold))))
   `(org-checkbox       ((t (:foreground ,orange :weight bold))))
   `(org-special-keyword ((t (:foreground ,gray :weight bold))))
   `(org-drawer         ((t (:foreground ,gray))))
   `(org-ellipsis       ((t (:foreground ,gray))))

   ;; --- markdown ---
   `(markdown-header-face           ((t (:foreground ,red :weight bold))))
   `(markdown-header-face-1         ((t (:foreground ,red :weight bold :height 1.2))))
   `(markdown-header-face-2         ((t (:foreground ,orange :weight bold :height 1.1))))
   `(markdown-header-face-3         ((t (:foreground ,yellow :weight bold))))
   `(markdown-header-face-4         ((t (:foreground ,green :weight bold))))
   `(markdown-header-delimiter-face ((t (:foreground ,red :weight bold))))
   `(markdown-code-face             ((t (:foreground ,yellow :background ,bg-dark))))
   `(markdown-inline-code-face      ((t (:foreground ,yellow))))
   `(markdown-pre-face              ((t (:foreground ,yellow :background ,bg-dark))))
   `(markdown-language-keyword-face ((t (:foreground ,cyan :weight bold))))
   `(markdown-link-face             ((t (:foreground ,purple :underline t))))
   `(markdown-url-face              ((t (:foreground ,gray :underline t))))
   `(markdown-bold-face             ((t (:foreground ,fg :weight bold))))
   `(markdown-italic-face           ((t (:foreground ,fg :slant italic))))
   `(markdown-list-face             ((t (:foreground ,red :weight bold))))
   `(markdown-markup-face           ((t (:foreground ,gray))))
   `(markdown-blockquote-face       ((t (:foreground ,gray :slant italic))))

   ;; --- web-mode / html / css / js (nvim HTML*/@tag eşlemesi) ---
   `(web-mode-html-tag-face            ((t (:foreground ,orange :weight bold))))
   `(web-mode-html-tag-bracket-face    ((t (:foreground ,gray-lt :weight bold))))
   `(web-mode-html-attr-name-face      ((t (:foreground ,green :weight bold))))
   `(web-mode-html-attr-value-face     ((t (:foreground ,yellow :weight bold))))
   `(web-mode-html-attr-equal-face     ((t (:foreground ,gray-lt))))
   `(web-mode-doctype-face             ((t (:foreground ,gray :slant italic))))
   `(web-mode-comment-face             ((t (:foreground ,gray :slant italic))))
   `(web-mode-string-face              ((t (:foreground ,yellow :weight bold))))
   `(web-mode-keyword-face             ((t (:foreground ,red :weight bold))))
   `(web-mode-type-face                ((t (:foreground ,cyan :slant italic :weight bold))))
   `(web-mode-function-name-face       ((t (:foreground ,green :weight bold))))
   `(web-mode-function-call-face       ((t (:foreground ,green :weight bold))))
   `(web-mode-variable-name-face       ((t (:foreground ,orange :weight bold))))
   `(web-mode-constant-face            ((t (:foreground ,purple :weight bold))))
   `(web-mode-builtin-face             ((t (:foreground ,cyan :weight bold))))
   `(web-mode-preprocessor-face        ((t (:foreground ,red :slant italic :weight bold))))
   `(web-mode-css-selector-face        ((t (:foreground ,red :weight bold))))
   `(web-mode-css-property-name-face   ((t (:foreground ,cyan :weight bold))))
   `(web-mode-css-string-face          ((t (:foreground ,yellow :weight bold))))
   `(web-mode-css-color-face           ((t (:foreground ,purple :weight bold))))
   `(web-mode-css-function-face        ((t (:foreground ,green :weight bold))))
   `(web-mode-symbol-face              ((t (:foreground ,orange :weight bold))))
   `(web-mode-block-delimiter-face     ((t (:foreground ,red :weight bold))))
   `(web-mode-block-control-face       ((t (:foreground ,red :weight bold))))
   `(web-mode-json-key-face            ((t (:foreground ,cyan :weight bold))))
   `(web-mode-json-string-face         ((t (:foreground ,yellow :weight bold))))
   `(css-selector       ((t (:foreground ,red :weight bold))))
   `(css-property       ((t (:foreground ,cyan :weight bold))))
   `(css-proprietary-property ((t (:foreground ,orange :weight bold))))
   `(nxml-element-local-name ((t (:foreground ,orange :weight bold))))
   `(nxml-attribute-local-name ((t (:foreground ,green :weight bold))))
   `(nxml-attribute-value ((t (:foreground ,yellow :weight bold))))
   `(nxml-tag-delimiter ((t (:foreground ,gray-lt))))
   `(nxml-comment-content ((t (:foreground ,gray :slant italic))))

   ;; --- rust / go / python (mode-specific, treesit de font-lock kullanır) ---
   `(rustic-string-interpolation-face ((t (:foreground ,orange :weight bold))))
   `(rust-question-mark ((t (:foreground ,red :weight bold))))
   `(rust-string-interpolation ((t (:foreground ,orange :weight bold))))
   `(rust-builtin-formatting-macro ((t (:foreground ,cyan :weight bold))))
   `(go-ts-mode-error-call-face ((t (:foreground ,red :weight bold))))
   `(go-ts-mode-error-type-face ((t (:foreground ,red :weight bold))))
   `(python-decorator-face ((t (:foreground ,orange :weight bold))))
   `(python-info-variable-name-face ((t (:foreground ,orange :weight bold))))

   ;; --- sh / conf / yaml / json / toml ---
   `(sh-quoted-exec     ((t (:foreground ,green :weight bold))))
   `(sh-heredoc         ((t (:foreground ,yellow :weight bold))))
   `(sh-escaped-newline ((t (:foreground ,orange))))
   `(conf-keyword-face  ((t (:foreground ,red :weight bold))))
   `(conf-variable-face ((t (:foreground ,orange :weight bold))))
   `(yaml-tab-face      ((t (:background ,red))))
   `(json-mode-object-name-face ((t (:foreground ,cyan :weight bold))))

   ;; --- treemacs / dired / dirvish ---
   `(treemacs-directory-face     ((t (:foreground ,cyan :weight bold))))
   `(treemacs-root-face          ((t (:foreground ,purple :weight bold :height 1.1))))
   `(treemacs-file-face          ((t (:foreground ,fg))))
   `(treemacs-git-modified-face  ((t (:foreground ,orange))))
   `(treemacs-git-untracked-face ((t (:foreground ,green))))
   `(treemacs-git-added-face     ((t (:foreground ,green))))
   `(treemacs-git-conflict-face  ((t (:foreground ,red))))
   `(treemacs-git-ignored-face   ((t (:foreground ,gray))))
   `(dired-directory    ((t (:foreground ,cyan :weight bold))))
   `(dired-symlink      ((t (:foreground ,cyan :slant italic))))
   `(dired-header       ((t (:foreground ,purple :weight bold))))
   `(dired-marked       ((t (:foreground ,orange :weight bold))))
   `(dired-flagged      ((t (:foreground ,red :weight bold))))
   `(dired-ignored      ((t (:foreground ,gray))))
   `(dired-perm-write   ((t (:foreground ,red))))
   `(diredfl-dir-name   ((t (:foreground ,cyan :weight bold))))
   `(diredfl-file-name  ((t (:foreground ,fg))))
   `(diredfl-file-suffix ((t (:foreground ,gray))))
   `(diredfl-exec-priv  ((t (:foreground ,green))))
   `(diredfl-read-priv  ((t (:foreground ,yellow))))
   `(diredfl-write-priv ((t (:foreground ,red))))
   `(diredfl-date-time  ((t (:foreground ,purple))))
   `(diredfl-number     ((t (:foreground ,purple))))
   `(diredfl-dir-heading ((t (:foreground ,purple :weight bold))))

   ;; --- eshell / term / vterm / ansi ---
   `(eshell-prompt      ((t (:foreground ,green :weight bold))))
   `(eshell-ls-directory ((t (:foreground ,cyan :weight bold))))
   `(eshell-ls-executable ((t (:foreground ,green :weight bold))))
   `(eshell-ls-symlink  ((t (:foreground ,cyan :slant italic))))
   `(eshell-ls-archive  ((t (:foreground ,purple :weight bold))))
   `(eshell-ls-backup   ((t (:foreground ,gray))))
   `(eshell-ls-clutter  ((t (:foreground ,red))))
   `(eshell-ls-missing  ((t (:foreground ,red :weight bold))))
   `(eshell-ls-product  ((t (:foreground ,orange))))
   `(eshell-ls-readonly ((t (:foreground ,yellow))))
   `(eshell-ls-special  ((t (:foreground ,orange :weight bold))))
   `(eshell-ls-unreadable ((t (:foreground ,gray))))
   `(comint-highlight-prompt ((t (:foreground ,green :weight bold))))
   `(comint-highlight-input  ((t (:foreground ,fg :weight bold))))
   `(term-color-black   ((t (:foreground ,bg-dark :background ,bg-dark))))
   `(term-color-red     ((t (:foreground ,red :background ,red))))
   `(term-color-green   ((t (:foreground ,green :background ,green))))
   `(term-color-yellow  ((t (:foreground ,yellow :background ,yellow))))
   `(term-color-blue    ((t (:foreground ,cyan :background ,cyan))))
   `(term-color-magenta ((t (:foreground ,purple :background ,purple))))
   `(term-color-cyan    ((t (:foreground ,cyan :background ,cyan))))
   `(term-color-white   ((t (:foreground ,fg :background ,fg))))
   `(ansi-color-black   ((t (:foreground ,bg-dark :background ,bg-dark))))
   `(ansi-color-red     ((t (:foreground ,red :background ,red))))
   `(ansi-color-green   ((t (:foreground ,green :background ,green))))
   `(ansi-color-yellow  ((t (:foreground ,yellow :background ,yellow))))
   `(ansi-color-blue    ((t (:foreground ,cyan :background ,cyan))))
   `(ansi-color-magenta ((t (:foreground ,purple :background ,purple))))
   `(ansi-color-cyan    ((t (:foreground ,cyan :background ,cyan))))
   `(ansi-color-white   ((t (:foreground ,fg :background ,fg))))
   `(ansi-color-bright-black   ((t (:foreground ,gray :background ,gray))))
   `(ansi-color-bright-red     ((t (:foreground ,red :background ,red))))
   `(ansi-color-bright-green   ((t (:foreground ,green :background ,green))))
   `(ansi-color-bright-yellow  ((t (:foreground ,yellow :background ,yellow))))
   `(ansi-color-bright-blue    ((t (:foreground ,cyan :background ,cyan))))
   `(ansi-color-bright-magenta ((t (:foreground ,purple :background ,purple))))
   `(ansi-color-bright-cyan    ((t (:foreground ,cyan :background ,cyan))))
   `(ansi-color-bright-white   ((t (:foreground ,fg :background ,fg))))

   ;; --- which-key / help / elisp ---
   `(which-key-key-face              ((t (:foreground ,orange :weight bold))))
   `(which-key-separator-face        ((t (:foreground ,gray))))
   `(which-key-command-description-face ((t (:foreground ,fg))))
   `(which-key-group-description-face ((t (:foreground ,purple))))
   `(help-key-binding ((t (:foreground ,orange :background ,bg-dark :box (:line-width -1 :color ,gray-dk)))))
   `(helpful-heading  ((t (:foreground ,purple :weight bold :height 1.1))))
   `(outline-1        ((t (:foreground ,red :weight bold))))
   `(outline-2        ((t (:foreground ,orange :weight bold))))
   `(outline-3        ((t (:foreground ,yellow :weight bold))))
   `(outline-4        ((t (:foreground ,green :weight bold))))
   `(outline-5        ((t (:foreground ,cyan :weight bold))))
   `(outline-6        ((t (:foreground ,purple :weight bold))))

   ;; --- ivy-free / misc doom ---
   `(doom-modeline-buffer-file      ((t (:foreground ,fg :weight bold))))
   `(doom-modeline-buffer-modified  ((t (:foreground ,orange :weight bold))))
   `(doom-modeline-buffer-path      ((t (:foreground ,cyan :weight bold))))
   `(doom-modeline-project-dir      ((t (:foreground ,green :weight bold))))
   `(doom-modeline-info             ((t (:foreground ,green))))
   `(doom-modeline-warning          ((t (:foreground ,orange))))
   `(doom-modeline-urgent           ((t (:foreground ,red))))
   `(doom-modeline-bar              ((t (:background ,orange))))
   `(doom-modeline-panel            ((t (:foreground ,bg :background ,orange :weight bold))))
   `(solaire-default-face           ((t (:background ,bg-dark :foreground ,fg))))
   `(solaire-hl-line-face           ((t (:background ,bg-light))))
   `(solaire-mode-line-face         ((t (:background ,ml-bg :foreground ,fg))))
   `(solaire-mode-line-inactive-face ((t (:background ,bg-dark :foreground ,gray))))

   ;; --- widget / custom ---
   `(widget-field       ((t (:foreground ,fg :background ,bg-light :box (:line-width 1 :color ,gray-dk)))))
   `(custom-button      ((t (:foreground ,bg :background ,gray-lt :box (:line-width 1 :style released-button)))))
   `(custom-variable-tag ((t (:foreground ,cyan :weight bold))))
   `(custom-state       ((t (:foreground ,green))))
   ))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'tugmonokai)
;;; tugmonokai-theme.el ends here
